Update clash version and build HDL in nix
clash-lang/stack-templates pull request #18
Opened 2022-11-11 15:23 UTC by rowanG077

2022-11-11 15:32 UTC, martijnbastiaan approved these changes
LGTM. @leonschoorl has been converted to the light side over the last half year, so I've asked him to review the nix stuff.

2022-11-12 12:43 UTC, martijnbastiaan commented
@rowanG077 Looks like CI integration with GitLab broke again. I'm moving us over to GHA over here: https://github.com/clash-lang/stack-templates/pull/19.

2022-11-12 14:23 UTC, rowanG077 commented
@martijnbastiaan Ah. I will rebase once that is merged!

2022-11-14 08:32 UTC, rowanG077 commented
@leonschoorl Rebase done. Once CI is happy this can be merged I think.

2022-11-14 16:27 UTC, leonschoorl requested changes
What do you think of this?

2022-11-14 16:27 UTC, leonschoorl commented on projects/simple-nix/default.nix
> +  hdl = "verilog";
```suggestion
  hdl = "verilog";
  topModule = "Example.Project";
```

Pull out the module name into a separate variable, to make it easier to change.

2022-11-15 10:49 UTC, rowanG077 commented
@leonschoorl I agree with your comments! I have applied them

2022-11-15 14:13 UTC, leonschoorl approved these changes
Thnx @rowanG077

2022-11-15 14:14 UTC, merged